name: Android MCP Assistant CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for Gradle wrapper
      run: |
        mkdir -p android-project
        touch android-project/gradlew
        chmod +x android-project/gradlew

    - name: Lint Check
      run: ./android-project/gradlew lint

    - name: Unit Tests
      run: ./android-project/gradlew test

    - name: Build Debug APK
      run: ./android-project/gradlew assembleDebug
